### PR TITLE
Denose

### PR DESCRIPTION
**Pull request by mcepl**
I am a maintainer of Python packages in openSUSE, and I am on my crusade of eliminating nose1 from our distribution. When I look at its repository on https://github.com/nose-devs/nose, the last release 1.3.7 was on 2 Jun 2015, and even the last commit on the master branch was on 4 Mar 2016. Moreover, apparently nose will finally stop working with python 3.10.

This PR removes the dependency on nose, not adding any additional dependency (works with `unittest` module from the standard library). Also, I have switched the directory layout of the package to the `src/`-based one for improved ease of testing.

### CODE REVIEW

**Comment by mcepl** [comment]
@jayvdb Could you take a look, please?

**Comment by jwilk** [comment]
> apparently nose will finally stop working with python 3.10.

FWIW, nose seems to work fine in Python 3.10 if you rebuild it from source.
See commit 8f88d3300e8a85ed0f974fbf75cfd80f8b53a0fc.

**Comment by mcepl** [comment]
Yes, without regards whether you can actually make nose work for you, the truth is that it is dead upstream and that you should move somewhere else. So, hopefully this PR is not completely useless.

**Comment by jwilk** [comment]
I took a different approach in 79e75bdd0bf1edcc11e6ffb36235513daf8fa85f.

**Pull request closed without merging**
